sudo: false
language: python
python: '3.6'
branches:
  except:
  - gh-pages
install:
- pip install tox "setuptools>=28.2"
- python setup.py -q build
- python setup.py -q install
- python setup.py -q publish
script: pytest
deploy:
  provider: pypi
  distributions: sdist --formats=zip bdist_wheel
  user: bspruth
  password:
    secure: 
  skip_upload_docs: true
  on:
    tags: true
    branch: master
    repo: target/threadfixproapi
